ALTER TABLE IF EXISTS d_patient
    DROP COLUMN IF EXISTS reserve1,
    DROP COLUMN IF EXISTS reserve2,
    DROP COLUMN IF EXISTS reserve3,
    DROP COLUMN IF EXISTS reserve4,
    DROP COLUMN IF EXISTS reserve5,
    DROP COLUMN IF EXISTS reserve6;
