ALTER TABLE IF EXISTS d_image
    ADD COLUMN IF NOT EXISTS uri VARCHAR(1024),
    ADD COLUMN IF NOT EXISTS digest VARCHAR(128);

ALTER TABLE IF EXISTS d_image
    ALTER COLUMN uri SET NOT NULL,
    ALTER COLUMN digest SET NOT NULL;

ALTER TABLE IF EXISTS d_image
    DROP COLUMN IF EXISTS jpegByte;

CREATE INDEX IF NOT EXISTS d_image_uri_idx
    ON d_image (uri);

CREATE INDEX IF NOT EXISTS d_image_digest_idx
    ON d_image (digest);
